name: clima
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.1
  http: ^1.2.2
  location: ^7.0.1
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
